import { Menu } from "./components";

export const data: Menu[] = [
  {
    id: 2,
    ref: 0,
    ruta: "/rrhh",
    expand: false,
    titulo: "RRHH",
    isModule: false,
    posicion: 2,
    protected: false,
    secciones: [
      {
        id: 11,
        ruta: "/solicitudrecibohaberes",
        titulo: "Haberes",
        iconname: "receipt",
        posicion: 1,
        protected: false,
        habilitado: false,
        descripcion: null,
      },
    ],
    habilitado: false,
  },
  {
    id: 3,
    ref: 0,
    ruta: "/ddjj",
    expand: false,
    titulo: "DDJJ",
    isModule: false,
    posicion: 3,
    protected: false,
    secciones: [
      {
        id: 12,
        ruta: "/ingresar",
        titulo: "DDJJ COM",
        iconname: "fact_check",
        posicion: 1,
        protected: false,
        habilitado: false,
        descripcion: null,
      },
    ],
    habilitado: false,
  },
  {
    id: 4,
    ref: 0,
    ruta: "/institucional",
    expand: false,
    titulo: "Institucional",
    isModule: false,
    posicion: 4,
    protected: false,
    secciones: [
      {
        id: 13,
        ruta: "/sueldos",
        titulo: "Sueldos",
        iconname: "description",
        posicion: 1,
        protected: false,
        habilitado: false,
        descripcion: null,
      },
      {
        id: 14,
        ruta: "/autoridades",
        titulo: "Autoridades",
        iconname: "groups",
        posicion: 2,
        protected: false,
        habilitado: false,
        descripcion: null,
      },
      {
        id: 15,
        ruta: "/expediente-movimientos",
        titulo: "Expedientes",
        iconname: "groups",
        posicion: 3,
        protected: false,
        habilitado: false,
        descripcion: null,
      },
    ],
    habilitado: false,
  },
  {
    id: 5,
    ref: 0,
    ruta: "/compras",
    expand: false,
    titulo: "Compras",
    isModule: false,
    posicion: 5,
    protected: false,
    secciones: [
      {
        id: 16,
        ruta: "/licitaciones",
        titulo: "Licitaciones",
        iconname: "discount",
        posicion: 1,
        protected: false,
        habilitado: false,
        descripcion: null,
      },
    ],
    habilitado: false,
  },
  {
    id: 6,
    ref: 0,
    ruta: "http://digesto.smandes.gov.ar/index_digesto.htm",
    expand: false,
    titulo: "Digesto",
    isModule: false,
    posicion: 6,
    protected: false,
    secciones: null,
    habilitado: false,
  },
  {
    id: 7,
    ref: 0,
    ruta: "http://boletinoficial.sanmartindelosandes.gov.ar",
    expand: false,
    titulo: "Boletín",
    isModule: false,
    posicion: 7,
    protected: false,
    secciones: null,
    habilitado: false,
  },
  {
    id: 1,
    ref: 0,
    ruta: "/rentas",
    expand: false,
    titulo: "Rentas",
    isModule: false,
    posicion: 1,
    protected: false,
    secciones: [
      {
        id: 9,
        ruta: "/adhesion",
        titulo: "Recibos",
        iconname: "attach_email",
        posicion: 2,
        protected: false,
        habilitado: false,
        descripcion: "null",
      },
      {
        id: 10,
        ruta: "/busqueda-comprobantes-de-pago",
        titulo: "Comprobantes",
        iconname: "receipt_long",
        posicion: 3,
        protected: false,
        habilitado: false,
        descripcion: "null",
      },
      {
        id: 8,
        ruta: "/pagar",
        titulo: "Pago Online",
        iconname: "fact_check",
        posicion: 1,
        protected: false,
        habilitado: false,
        descripcion: "null",
      },
    ],
    habilitado: false,
  },
];
