export interface RestaurantMenu {
  array: ArrayClass;
}

export interface ArrayClass {
  type: string;
  "restaurant-info": RestaurantInfo;
  "restaurant-time-info": RestaurantTimeInfo;
  today: string;
  "working-hours-start": string;
  "working-hours-end": string;
  categorys: Category[];
  deals: any[];
}

export interface Category {
  id: string;
  name: string;
  position: string;
  "menu-items": MenuItem[];
}

export interface MenuItem {
  id: string;
  name: string;
  position: number;
  description: string;
  images: any[];
  "sub-items": SubItem[];
}

export interface SubItem {
  id: string;
  name: string;
  position: number;
  price: string;
  consumable: Consumable;
  cuisine_name: CuisineName;
  category_name: string;
  discount: Discount;
  tags: any[];
}

export enum Consumable {
  The11 = "1:1",
  The13 = "1:3",
  The14 = "1:4",
  The16 = "1:6",
}

export enum CuisineName {
  Burger = "Burger",
  Desserts = "Desserts",
  FastFood = "Fast Food",
  Indian = "Indian",
  Salad = "Salad",
}

export interface Discount {
  type: string;
  amount: string;
}

export interface RestaurantInfo {
  id: string;
  sponsored: string;
  "user-favourite": string;
  name: string;
  address: string;
  rating: string;
  "minimum-order-price": string;
  "delivery-fee": string;
  avg_delivery_time: string;
  logo: string;
  "open-status": string;
  "default-ad": string;
  "review-enabled": string;
  "social-share": string;
  value: null;
  "total-category": string;
  "site-url": string;
  "location-img": string;
  "restaurant-url": string;
  "payment-methods": PaymentMethod[];
  "delivery-types": string;
  tags: any[];
  "deliverable-area": DeliverableArea[];
  ratings: Rating[];
  "total-food-items": string;
  "facebook-like-link": string;
  description: string;
  "restaurant-discount": RestaurantDiscount;
  "restaurant-images": string[];
}

export interface DeliverableArea {
  id: string;
  name: string;
}

export interface PaymentMethod {
  id: string;
  type: string;
}

export interface Rating {
  rating: string;
}

export interface RestaurantDiscount {
  type: string;
  value: string;
}

export interface RestaurantTimeInfo {
  sat: Fri[];
  sun: Fri[];
  mon: Fri[];
  tue: Fri[];
  wed: Fri[];
  thu: Fri[];
  fri: Fri[];
}

export interface Fri {
  open: string;
  close: string;
}

// Menu Test
// Generated by https://quicktype.io

export interface Items {
  title: string;
  children?: ItemsChild[];
}

export interface ItemsChild {
  title: string;
  children?: ChildChild[];
}

export interface ChildChild {
  title: string;
}
